#!/bin/bash

# Configure networking parameters.
sysctl net.ipv4.ip_forward=1
RULE="PREROUTING -t nat -p tcp --dport 80 -j REDIRECT --to-port 3128
if ! iptables -C ${RULE};
then
    iptables -I ${RULE}
fi

# Start services.
service cron start
service squid3 start

# Update blacklists.
afprx-update
